### ISSUE TITLE
not showing up

### ISSUE THREAD

**Issue by hjanuschka** [neos/form-builder#132]
most likely its my own fault.

but i followed the setup guid for neoscms here -> https://docs.neos.io/guide/installation-development-setup/manual-setup/mac-os-linux-using-the-embedded-web-server

and installed form-builder using

```
composer require neos/form-builder
```

and i cannot see a form "node" as shown in the screenshot on the README.md
any hints on where to further debug this ?

**Comment by bwaidelich** [comment]
You mean, you can't find the "Form" element in the "Create Node Wizard" as shown here:
![image](https://github.com/neos/form-builder/assets/307571/de18abc4-c22e-4ce7-98c1-7e89ab9e89f3)
?

Maybe try:
* Flushing caches (`./flow flow:cache:flush`)
* Rescanning installed packages (`./flow flow:package:rescan`)
* Check whether nodes of the type `Neos.Form.Builder:NodeBasedForm` are allowed at the place where you wanted to insert the form (see https://docs.neos.io/guide/manual/content-repository/nodetype/node-constraints)

**Comment by hjanuschka** [comment]
tried all of it, tbh not yet fully aware of node constraints, such a painfull xp.
installed the demo site package.

and tried inserting a node ("+") on each of this levels.

<img width="330" alt="image" src="https://github.com/neos/form-builder/assets/2891702/4e6e9877-a59d-4016-b29b-bccd171016fc">

is it the demo site? do you have any other suggestion? in fact i just wan't to build a custom form field - and that is my first touchpoint with neos.

**Comment by bwaidelich** [comment]
> not yet fully aware of node constraints, such a painfull xp

It might be painful to get to know the concepts, but node constraints actually provide great flexibility and XP to the editors because they don't have to think of impossible content element combinations.

> is it the demo site?

I don't know, you should know :)
But judging from the node title, it looks like it _is_.

> and tried inserting a node ("+") on each of this levels.

The form builder is a content element so you want to add it in one of the Content Collections. But you won't have to use the Structure tree for that. Instead in your content area you should see placeholders that allow you to insert new content elements directly inline.

**Comment by hjanuschka** [comment]
> demosite
sorry that might have been miss communicated, i have the demo site, meant if it could be related to the use of the demo site.


ok it does not show up :( 
added a new blank page - and think that should be the right place where it should be available


<img width="1480" alt="image" src="https://github.com/neos/form-builder/assets/2891702/090575c6-9966-4caf-a633-0010008adda9">


`nodetype:list`

shows the ones that look like are the right ones.:
<img width="834" alt="image" src="https://github.com/neos/form-builder/assets/2891702/511b49a1-863c-4390-9c22-f7488e6f6d92">

**Comment by hjanuschka** [comment]
other question, do you have some sort of testing repo that could be used as a starter? (maybe something you use in CI ?)

**Comment by bwaidelich** [comment]
> nodetype:list

Returns a list of all configured node types, ignoring their constraints.

The `Neos.Demo` site comes with quite some restrictive constraints to demonstrate the concept, but frankly that is not very helpful when trying to get something up and running.


> other question, do you have some sort of testing repo that could be used as a starter?

Not really. For CI we use the demo site in order to test common use cases. But to get started, I would suggest, you start with a blank site, which won't have any NodeType constraints predefined.

With the demo site installed, you first have to explicitly allow new content element, for example within multi-column containers:

https://github.com/neos/form-builder/assets/307571/41db421e-ae93-4817-a6a1-73f0752583d5

Alternatively, you can create a custom `NodeTypes.yaml` file underneath `/Configuration`  with:

```yaml
'Neos.Form.Builder:NodeBasedForm':
  superTypes:
    'Neos.Demo:Constraint.Content.Column': true
```

HTH

**Comment by hjanuschka** [comment]
awesome, that works!
many thanks for your effort, even doing a video, and sorry for me asking stupid questions!
