### ISSUE TITLE
Form elements in sections cannot be reordered using the structure tree

### ISSUE THREAD

**Issue by lorenzulrich** [neos/form-builder#20]
Form elements in a section can be moved, but apart from reloading the frontend, nothing happens (no applicable change that would actually lead to the desired sorting).

This only happens in the new UI.

**Comment by bwaidelich** [comment]
Probably related with #17

**Comment by skurfuerst** [comment]
I am quite certain this is fixed by https://github.com/neos/neos-ui/pull/1693 - could you add this PR and check if this fixes the issue? Unfortunately I have not so much time currently, so I can't really promise when in the next days I check out the form builder and test it.

All the best,
Sebastian

**Comment by skurfuerst** [comment]
validated. Fixed by https://github.com/neos/neos-ui/pull/1693

**Comment by bwaidelich** [comment]
Fixed with Neos 3.3.9
(but unfortunately that version introduced a "regression", see #21, so I would not recommend to update yet if you are using the Form Builder)
