### ISSUE TITLE
NodeBasedFinisher Properties are not merged correctly

### ISSUE THREAD

**Issue by gradinarufelix** [neos/form-builder#41]
Since Neos 4.3 the properties of a NodeBasedFinishers are being appended to the default properties array instead of being merged, see image. The relevant part in the Fusion declaration is in NodeBasedFinisher.fusion:

`
prototype(Neos.Form.Builder:NodeBasedFinisher) < prototype(Neos.Fusion:Renderer) {
    element {
        @context.finisher = ${this}
        options.@process.addNodeProperties = ${Array.concat(value, finisherNode.properties)}
    }
}
`

It could be that ArrayPropertyCollection doesn't play nicely with Array.concat. Below you see the var_dump of `$this->options` from the finisher class. The properties are added as a sub-array instead being merged with the default values

![var_dump of `$this->options` from the finisher class. The properties are added as a sub-array instead being merged with the default values](https://user-images.githubusercontent.com/4405087/56641586-fa6a7b80-6675-11e9-96c2-e5f8e102c0d0.png)

**Comment by bwaidelich** [comment]
@gradinarufelix Thanks for creating the issue. I can reproduce the problem and try to work it out now

**Comment by bwaidelich** [comment]
The reason this fails (and some more related things) is that PR in `Neos.ContentRepository`: https://github.com/neos/neos-development-collection/pull/2202
It changes the return type of `Node::getProperties()` from an array to an object implementing `PropertyCollectionInterface` so all array operations fail.

I'm not perfectly sure how to solve this.. I suppose that this has many more side effects so we might consider some tweaks in the Neos packages.
For example we could adjust the `ArrayHelper` functions so that they work with `iterables`, too.

But as a hotfix we can probably replace all the `@process.addNodeProperties.` instances (three of them) with some custom fusion

**Comment by bwaidelich** [comment]
@gradinarufelix not the nicest solution, but #42 seems to work.. Maybe we can tweak that a bit

**Comment by gradinarufelix** [comment]
Looks good. Definitely the best thing we can do in this package. Thanks for the quick fix. Do you know when it will be merged?

**Comment by bwaidelich** [comment]
@gradinarufelix Thanks for checking. I tweaked the PR a bit (just adding doc comments). Can you please +1 it if it works for you?
